return {
	override_enabled = true,
	preset = "SURVIVAL_TOGETHER", 		-- "SURVIVAL_TOGETHER", "MOD_MISSING", "SURVIVAL_TOGETHER_CLASSIC", "SURVIVAL_DEFAULT_PLUS", "COMPLETE_DARKNESS", "DST_CAVE", "DST_CAVE_PLUS"
	overrides = {
		-- MISC
		task_set = "default", 			-- 生物群落 "classic", "default", "cave_default"
		start_location = "default", 	-- 初始环境 "caves", "default", "plus", "darkness"
		world_size = "default", 		-- 世界大小 "small", "medium", "default", "huge"
		branching = "default", 			-- 岔路地形 "never", "least", "default", "most"
		loop = "default", 				-- 环状地形 "never", "default", "always"
		specialevent = "default",       -- 活动 "none", "default", "hallowed_nights", "winters_feast", "year_of_the_gobbler"
		autumn = "default", 			-- 秋天 "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
		winter = "default", 			-- 冬天 "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
		spring = "default", 			-- 春天 "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
		summer = "default", 			-- 夏天 "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
		season_start = "default", 		-- 初始季节 "default", "winter", "spring", "summer", "autumnorspring", "winterorsummer", "random"
		day = "default", 				-- 时长 "default", "longday", "longdusk", "longnight", "noday", "nodusk", "nonight", "onlyday", "onlydusk", "onlynight"
		weather = "default", 			-- 雨 "never", "rare", "default", "often", "always"
		lightning = "default", 			-- 闪电 "never", "rare", "default", "often", "always"
		frograin = "default", 			-- 青蛙雨 "never", "rare", "default", "often", "always"
		wildfires = "default", 			-- 自燃 "never", "rare", "default", "often", "always"
		regrowth = "default", 			-- 世界再生 "veryslow", "slow", "default", "fast", "veryfast"
		touchstone = "default", 		-- 试金石 "never", "rare", "default", "often", "always"
		boons = "default", 				-- 前辈 "never", "rare", "default", "often", "always"
		disease_delay = "default", 		-- 疾病 "none", "random", "long", "default", "short"
		prefabswaps_start = "default", 	-- 初始多样性 "classic", "default", "highly random"
		petrification = "default", 		-- 石化树 "none", "few", "default", "many", "max"

		-- RESOURCES
		flowers = "default", 			-- 花、恶魔花 "never", "rare", "default", "often", "always"
		grass = "default", 				-- 草 "never", "rare", "default", "often", "always"
		sapling = "default", 			-- 树苗 "never", "rare", "default", "often", "always"
		marshbush = "default", 			-- 尖刺灌木 "never", "rare", "default", "often", "always"
		tumbleweed = "default", 		-- 风滚草 "never", "rare", "default", "often", "always"
		reeds = "default", 				-- 芦苇 "never", "rare", "default", "often", "always"
		trees = "default", 				-- 树（全）"never", "rare", "default", "often", "always"
		flint = "default", 				-- 燧石 "never", "rare", "default", "often", "always"
		rock = "default", 				-- 卵石 "never", "rare", "default", "often", "always"
		rock_ice = "default", 			-- 迷你冰川 "never", "rare", "default", "often", "always"
		meteorspawner = "default", 		-- 流星区域 "never", "rare", "default", "often", "always"
		meteorshowers = "default", 		-- 流星频率 "never", "rare", "default", "often", "always"

		-- UNPREPARED
		berrybush = "default", 			-- 浆果丛 "never", "rare", "default", "often", "always"
		carrot = "default", 			-- 胡萝卜 "never", "rare", "default", "often", "always"
		mushroom = "default", 			-- 蘑菇 "never", "rare", "default", "often", "always"
		cactus = "default", 			-- 仙人球 "never", "rare", "default", "often", "always"

		-- ANIMALS
		rabbits = "default", 			-- 兔子 "never", "rare", "default", "often", "always"
		moles = "default", 				-- 鼹鼠 "never", "rare", "default", "often", "always"
		butterfly = "default", 			-- 蝴蝶 "never", "rare", "default", "often", "always"
		birds = "default", 				-- 鸟 "never", "rare", "default", "often", "always"
		buzzard = "default", 			-- 秃鹰 "never", "rare", "default", "often", "always"
		catcoon = "default", 			-- 浣猫 "never", "rare", "default", "often", "always"
		perd = "default", 				-- 火鸡 "never", "rare", "default", "often", "always"
		pigs = "default", 				-- 猪人 "never", "rare", "default", "often", "always"
		lightninggoat = "default", 		-- 伏特羊 "never", "rare", "default", "often", "always"
		beefalo = "default", 			-- 皮弗娄牛 "never", "rare", "default", "often", "always"
		beefaloheat = "default", 		-- 皮弗娄牛交配（红屁股）的频率"never", "rare", "default", "often", "always"
		hunt = "default", 				-- 足迹 "never", "rare", "default", "often", "always"
		alternatehunt = "default", 		-- 彩蛋 "never", "rare", "default", "often", "always"
		penguins = "default", 			-- 企鹅 "never", "rare", "default", "often", "always"
		ponds = "default", 				-- 池塘 "never", "rare", "default", "often", "always"
		bees = "default", 				-- 蜜蜂 "never", "rare", "default", "often", "always"
		angrybees = "default", 			-- 杀人蜂 "never", "rare", "default", "often", "always"
		tallbirds = "default", 			-- 高鸟 "never", "rare", "default", "often", "always"

		-- MONSTERS
		spiders = "default", 			-- 蜘蛛 "never", "rare", "default", "often", "always"
		hounds = "default", 			-- 猎犬攻击 "never", "rare", "default", "often", "always"
		houndmound = "default", 		-- 猎犬丘 "never", "rare", "default", "often", "always"
		merm = "default", 				-- 鱼人 "never", "rare", "default", "often", "always"
		tentacles = "default", 			-- 触手 "never", "rare", "default", "often", "always"
		chess = "default", 				-- 发条生物 "never", "rare", "default", "often", "always"
		lureplants = "default", 		-- 食人花 "never", "rare", "default", "often", "always"
		walrus = "default", 			-- 海象巢穴 "never", "rare", "default", "often", "always"
		liefs = "default", 				-- 树精守卫 "never", "rare", "default", "often", "always"
		deciduousmonster = "default", 	-- 桦树精 "never", "rare", "default", "often", "always"
		krampus = "default", 			-- 坎普斯 "never", "rare", "default", "often", "always"
		bearger = "default", 			-- 熊獾 "never", "rare", "default", "often", "always"
		deerclops = "default", 			-- 独眼巨鹿 "never", "rare", "default", "often", "always"
		goosemoose = "default", 		-- 鹿角鹅 "never", "rare", "default", "often", "always"
		dragonfly = "default", 			-- 龙蝇 "never", "rare", "default", "often", "always"
		antliontribute = "default", 	-- 蚁狮恩惠 "never", "rare", "default", "often", "always"
	},
}